# Logistic Regression model/Sigmoid/Binary classification
### To answer a Boolean question – Yes/No | 0/1 | True/False
Also works with multiclass problems (Not reccomenfded). The model will do 1 VS ALL <br>

In [2]:
import pandas as pd
import numpy as np
import sklearn as skl

Load the dataset

In [3]:
df = pd.read_csv('../../Datasets/emails.csv')
df.head(1)

email  rec  elen  attch  slen  spam
0  eli302@outlook.com   10   235      1    35     1

## Split to - X(Train), Y(Test) 
Create an X array that contains the features to train on, and a y array with the target variable - the Price column.
While we remove any non valuable data.
### Use sklearn.model_selection.train_test_split to split the data (train/test)
We split the data to 70% and 30% , run the model on 70% data, and then test on the 30% and see if the results are close to the real values. 

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['email','spam'],axis=1), 
                                                    df['spam'], test_size=0.30, 
                                                    random_state=101)

## Create the Model

In [15]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression()

## Train the Model
We send it the X and the Y and it findes the A , B (from Y = AX + B).

In [19]:
model.fit(X_train,y_train)

c:\users\lanyado\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## Information about the Model

Display the model coefficient/weiht. (The A from Y = AX + B).<br><br>
If one of the coefs is really small we can delete his feature from the dataset, and retrain the model.<br>
But, first have to check that this column doesn't have big numbers (like a salary), and than it's fine that it's coef is small.

In [35]:
model.coef_

array([[ 0.24287163,  0.00444749, -0.02290707,  0.05551722]])

Display the model intercept/bias (The B from Y = AX + B).<br>
The minimum value of every y (In this exmple, the minimum cose of every house).

In [21]:
model.intercept_

array([-4.02153134])

## Test the Model

Predict the test set, and than check it to decide if the model is good.<br>
The function takes the value and outputs it to be between 0 and 1. <br>
`Y < 0.5` => 0<br>
`Y > 0.5` => 1

In [22]:
predictions = model.predict(X_test)

### Score 
A Math mathod (A precent of 100) <br>
**Be Carful!** when the score is 99% it can be a lie - because it will say only false, and never true.<br>
It happens in situations when most of the dataset is false and just a litlle is true.<br>
Like:<br>
* Should I give a costumer a premium account
* Should I send a person toa rare check
* Will the costumerwill buy a really expencive product<br><br>
**Solutions:**
* Try another model.<br>
* `Undersampling`/`Oversampling` - packages in pypi, that multiply the amount of the true to the amount we want.
https://www.kaggle.com/residentmario/undersampling-and-oversampling-imbalanced-data<br>
https://medium.com/anomaly-detection-with-python-and-r/sampling-techniques-for-extremely-imbalanced-data-part-i-under-sampling-a8dbc3d8d6d8

In [32]:
model.score(X_test,y_test)

0.8699029126213592

### confusion_matrix
Because of the score problem, we use a confusion_matrix.<br>
When there aren't numbers on the right column it means that the model never said False.<br>
We want to see numbers only on the main diagonal, and that the rest eill be zeros.
# TN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FP  
**True Negative**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
**False Positive**<br>
(The model said 0 and it's TRUE)&nbsp;&nbsp;&nbsp;&nbsp;(The model said 1 and it's FALSE)

# FN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TP
**False Negative**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
**True Positive**<br>
(The model said 0 and it's FALSE)&nbsp;&nbsp;&nbsp;&nbsp;(The model said 0 and it's TRUE)

In [33]:
import sklearn.metrics as skmet
skmet.confusion_matrix(y_test,predictions)

array([[367,   0],
       [ 67,  81]], dtype=int64)

### classification_report

**Accurancy** - (TN +TP)/TOTAL | Like the score, it's good when the False and True values in the dataseet are equal.<br>
**Recall**/Positive rate/Sensitivity - TP / (FN + TP) | The precent of the trues it found of all of the trues (How many sick people it recognised of all the sick people- 100% is necessary. How many spam mails it recognised of all the spam mails- 100% isn't necessary)<br>
**Precision** - TP / (FP + TP) | Actual yes / Total perdicted yes<br>
The precent of the real trues it found of all of the trues it found (How many sick people it recognised that are really sick - 100% is not necessary. How many spam mails it recognised hat are real spam - 100% is necessary)<br>
**F1-score** - 2*((Precision*Recall)/(Precision + Recall))

In [34]:
print(skmet.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92       367
           1       1.00      0.55      0.71       148

    accuracy                           0.87       515
   macro avg       0.92      0.77      0.81       515
weighted avg       0.89      0.87      0.86       515

