In [2]:
#!pip install numpy
import numpy as np

In [3]:
regular_list = [1,2,3]

In [4]:
np.array(regular_list) # Type = numpy.ndarray
np.array([1,2,3]) # Type = numpy.ndarray

array([1, 2, 3])

In [13]:
# When the steps is important for me
np.arange(1,10,2) # (Start, Stop, Steps)

array([1, 3, 5, 7, 9])

In [16]:
# When the min and max are important for me
np.linspace(1,10,3) # (Min, Max, number of values)

array([ 1. ,  5.5, 10. ])

In [18]:
np.zeros((2,3)) # Create an array with 5 columns and 3 rows includes only zeros 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3)) # Create an array with 5 columns and 3 rows includes only ones 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones((2,3)) * 7 # Create an array with 5 columns and 3 rows includes only sevens 

array([[7., 7., 7.],
       [7., 7., 7.]])

In [21]:
np.eye(3) # Return a 2-D array with ones on the diagonal (אלכסון) and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#Extract a diagonal from an array or construct a diagonal array from just an array
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
# make a new array with (first column, second column, thierd column...)
np.column_stack((heights,weights,bmi))