In [1]:
#!pip install numpy
import numpy as np

In [34]:
# Generates 5 random numbers sampled from a standard normal distribution close to 0
np.random.randn(5)
# Its basiclly the same, but - https://stackoverflow.com/questions/21738383/python-difference-between-randn-and-normal

array([ 0.88995643,  0.97628374,  0.73767342,  1.32020101, -1.17755195])

In [6]:
#Generates a random number between 0 and 1
np.random.rand()
#Generates a list of 5 random numbers between 0 and 1
np.random.rand(5)

array([0.89074821, 0.28218288, 0.49015564, 0.99885046, 0.38464995])

In [3]:
#Generate a random number between 10 and 19
np.random.randint(10,20)
#Generate an array of 5 random numbers between 10 and 19
np.random.randint(10,20,5)
#Generates ints between 0 and 225 to a two dimensions array with 5 columns and 3 rows
np.random.randint(0,256,[3,5])

array([[245, 184,  90, 215,  33],
       [ 29, 223, 155, 133, 200],
       [105, 154,  61, 205,  97]])

In [5]:
#Generates an array [2,5] with random floats between 0 and 100
np.random.uniform(0,100,[2,5])

array([[10.08041829, 86.7888973 ,  0.1667386 , 35.2589026 , 24.09995815],
       [35.05753163, 61.33448995,  7.91356642, 28.59450204, 21.77742918]])

In [36]:
# התפלגות גאוסית (פעמון)/התפלגות נורמאלית
# Sampled numbers from a standard normal distribution
# Generates 5 numbers that most of them will be between 1.65 to 1.85
np.random.normal(1.75, 0.1, 5)

array([1.65885686, 1.86636758, 1.72411163, 2.05693741, 1.7029568 ])

In [7]:
#Generates an array of 5 random Values - A/B/C (Because thats what we gave it)
np.random.choice(['A','B','C'],5)

array(['A', 'A', 'A', 'A', 'B'], dtype='<U1')

In [ ]:
#Makes every random after it returns the same answer every time, because the random will always start from that point
np.random.seed(300)